package GameEntity.GameTile.Tower;

public interface TowerProperty {
    int NORMAL_TOWER_RANGE = 80;
    int NORMAL_TOWER_ATTACKRATE = 10;
    int NORMAL_TOWER_COST = 100;
    int NORMAL_TOWER_WIDTH = 30;
    int NORMAL_TOWER_HEIGHT = 30;

    int SMALLER_TOWER_RANGE = 70;
    int SMALLER_TOWER_ATTACKRATE = 6;
    int SMALLER_TOWER_COST = 150;
    int SMALLER_TOWER_WIDTH = 20;
    int SMALLER_TOWER_HEIGHT = 20;

    int SNIPER_TOWER_RANGE = 110;
    int SNIPER_TOWER_ATTACKRATE = 15;
    int SNIPER_TOWER_COST = 170;
    int SNIPER_TOWER_WIDTH = 45;
    int SNIPER_TOWER_HEIGHT = 45;
}
