package GameEntity.GameTile.Tower;

public interface TowerProperty {
    int NORMAL_TOWER_RANGE = 150;
    int NORMAL_TOWER_ATTACK_RATE = 10;
    int NORMAL_TOWER_COST = 100;
    int NORMAL_TOWER_WIDTH = 30;
    int NORMAL_TOWER_HEIGHT = 30;

    int SMALLER_TOWER_RANGE = 130;
    int SMALLER_TOWER_ATTACK_RATE = 6;
    int SMALLER_TOWER_COST = 150;
    int SMALLER_TOWER_WIDTH = 20;
    int SMALLER_TOWER_HEIGHT = 20;

    int SNIPER_TOWER_RANGE = 170;
    int SNIPER_TOWER_ATTACK_RATE = 15;
    int SNIPER_TOWER_COST = 170;
    int SNIPER_TOWER_WIDTH = 45;
    int SNIPER_TOWER_HEIGHT = 45;

    int INFERNO_TYPE1_RANGE = 160;
    int INFERNO_TYPE2_RANGE = 150;
    int INFERNO_ATTACK_RATE = 10;
    int INFERNO_TOWER_COST = 250;
    int INFERNO_TOWER_WIDTH = 40;
    int INFERNO_TOWER_HEIGHT = 40;
    int INFERNO_TOWER_MAX_TARGET = 5;
}
