package GameEntity.Bullet;

public interface BulletProperty{
	double NORMAL_BULLET_SPEED = 10;
    double NORMAL_BULLET_DAMAGE = 30;
    double NORMAL_BULLET_WIDTH = 9;
    double NORMAL_BULLET_HEIGHT = 9;

    double MACHINE_GUN_BULLET_SPEED = 15;
    double MACHINE_GUN_BULLET_DAMAGE = 20;
    double MACHINE_GUN_BULLET_WIDTH = 6;
    double MACHINE_GUN_BULLET_HEIGHT = 6;

    double SNIPER_BULLET_SPEED = 15;
    double SNIPER_BULLET_DAMAGE = 50;
    double SNIPER_BULLET_WIDTH = 12;
    double SNIPER_BULLET_HEIGHT = 12;

    double INFERNO_BULLET_TYPE1_DAMAGE = 18;
    double INFERNO_BULLET_TYPE2_MIN_DAMAGE = 15;
    double INFERNO_BULLET_TYPE2_MAX_DAMAGE = 70;
    double INFERNO_BULLET_WIDTH = 10;
    double INFERNO_BULLET_HEIGHT = 10;
}